import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f4f7f3',
  },
  content: {
    padding: 20,
    paddingBottom: 36,
    gap: 16,
  },
  hero: {
    paddingTop: 18,
    gap: 8,
  },
  kicker: {
    color: '#2f6f4e',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: '#16211b',
    fontSize: 38,
    fontWeight: '900',
    letterSpacing: 0,
  },
  subtitle: {
    color: '#52605a',
    fontSize: 16,
    lineHeight: 23,
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  metric: {
    flex: 1,
    minHeight: 78,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dde6dd',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  metricValue: {
    color: '#172019',
    fontSize: 24,
    fontWeight: '900',
  },
  metricLabel: {
    color: '#6d7771',
    fontSize: 12,
    marginTop: 2,
    textTransform: 'uppercase',
  },
  panel: {
    gap: 12,
  },
  sectionTitle: {
    color: '#172019',
    fontSize: 18,
    fontWeight: '900',
  },
  segmented: {
    height: 48,
    width: 288,
    borderRadius: 8,
    backgroundColor: '#e1e9e1',
    flexDirection: 'row',
    overflow: 'hidden',
    position: 'relative',
  },
  segmentIndicator: {
    position: 'absolute',
    left: 4,
    top: 4,
    width: 88,
    height: 40,
    borderRadius: 7,
  },
  segment: {
    width: 96,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentText: {
    color: '#506057',
    fontSize: 13,
    fontWeight: '800',
  },
  segmentTextActive: {
    color: '#ffffff',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  primaryActionWrap: {
    flex: 1,
  },
  primaryAction: {
    height: 56,
    borderRadius: 8,
    backgroundColor: '#172019',
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryActionText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  secondaryAction: {
    height: 56,
    minWidth: 96,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#bdcabc',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  secondaryActionText: {
    color: '#243028',
    fontSize: 15,
    fontWeight: '800',
  },
  previewPanel: {
    backgroundColor: '#172019',
    borderRadius: 8,
    overflow: 'hidden',
  },
  previewImage: {
    width: '100%',
    height: 230,
  },
  previewCopy: {
    padding: 16,
    gap: 4,
  },
  previewTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '900',
  },
  previewText: {
    color: '#c8d6ce',
    fontSize: 14,
  },
  previewHint: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 6,
  },
  emptyState: {
    minHeight: 150,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ccd9ca',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    gap: 6,
  },
  emptyTitle: {
    color: '#18251d',
    fontSize: 18,
    fontWeight: '900',
  },
  emptyText: {
    color: '#66726b',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  entriesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  counter: {
    color: '#68746d',
    fontWeight: '800',
  },
  entryCard: {
    minHeight: 104,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dde6dd',
    overflow: 'hidden',
  },
  entryPressable: {
    flexDirection: 'row',
    minHeight: 104,
  },
  entryImage: {
    width: 104,
    height: 104,
  },
  entryInfo: {
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
    alignItems: 'center',
  },
  moodDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  entryTextBlock: {
    flex: 1,
    gap: 3,
  },
  entryTitle: {
    color: '#172019',
    fontSize: 16,
    fontWeight: '900',
  },
  entryMeta: {
    color: '#66726b',
    fontSize: 12,
  },
  entryHint: {
    color: '#2f6f4e',
    fontSize: 12,
    fontWeight: '800',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(12, 18, 14, 0.72)',
    justifyContent: 'flex-end',
  },
  detailSheet: {
    maxHeight: '92%',
    backgroundColor: '#f4f7f3',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    overflow: 'hidden',
  },
  detailImage: {
    width: '100%',
    height: 290,
  },
  detailBody: {
    padding: 18,
    paddingBottom: 34,
    gap: 14,
  },
  detailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  detailTitle: {
    color: '#172019',
    fontSize: 24,
    fontWeight: '900',
  },
  detailMeta: {
    color: '#66726b',
    fontSize: 13,
    marginTop: 2,
  },
  closeButton: {
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#bdcabc',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  closeButtonText: {
    color: '#243028',
    fontWeight: '900',
  },
  placeBox: {
    borderRadius: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dde6dd',
    padding: 14,
    gap: 4,
  },
  placeLabel: {
    color: '#6d7771',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  placeText: {
    color: '#172019',
    fontSize: 15,
    fontWeight: '800',
  },
  inputLabel: {
    color: '#172019',
    fontSize: 15,
    fontWeight: '900',
  },
  descriptionInput: {
    minHeight: 104,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#bdcabc',
    color: '#172019',
    fontSize: 15,
    lineHeight: 21,
    padding: 14,
  },
  characterCounter: {
    color: '#66726b',
    fontSize: 12,
    textAlign: 'right',
    marginTop: -8,
  },
  saveButton: {
    height: 52,
    borderRadius: 8,
    backgroundColor: '#172019',
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
  cameraScreen: {
    flex: 1,
    backgroundColor: '#000000',
  },
  camera: {
    flex: 1,
  },
  cameraOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'space-between',
    padding: 20,
  },
  cameraTopBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ghostButton: {
    height: 44,
    borderRadius: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  ghostButtonText: {
    color: '#ffffff',
    fontWeight: '900',
  },
  cameraMood: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
    textShadowColor: 'rgba(0, 0, 0, 0.55)',
    textShadowRadius: 8,
  },
  shutterOuter: {
    alignSelf: 'center',
    marginBottom: 18,
  },
  shutter: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shutterCore: {
    width: 58,
    height: 58,
    borderRadius: 29,
    borderWidth: 3,
    borderColor: '#172019',
  },
});
